### ISSUE TITLE
SD card not recognized

### ISSUE THREAD

**Issue by normous** [CEbbinghaus/MicroSDeck#9] opened 2023-11-26 07:28 UTC
First of all: thank you so much for making this. It is brilliant, and exactly what I've been dreaming of to help juggle multiple SD cards.

The issue I'm having: I have 4 SD cards. 3 of them (2 512GB and 1 256GB) work flawlessly. They were recognized and cataloged correctly. The 4th is a 1TB card that is brand new. Prior to inserting it for the first time I had already installed the MicroSDeck plugin. I inserted the SD card and formatted it. It does not show up in the MicroSDeck config.

I have elected/reinserted it multiple times, swapping out for one of the other 3. I have rebooted my deck. Can't get it to show up. Otherwise it works normally with the deck.

Please let me know if there is any logging or troubleshooting I can do on my end to assist.

**Comment by CEbbinghaus** [comment] 2023-11-27 07:05
Wonderful. Thank you for raising this Issue <3. The logs should be located under `~/homebrew/data/MicroSDeck/logs`. Please do post them here. Also let me know if you are using the Store version or one of the prerelease versions?

**Comment by normous** [comment] 2023-11-28 05:41
[backend.log](https://github.com/CEbbinghaus/MicroSDeck/files/13483872/backend.log)
To my eyes nothing crazy jumps out from the log.

I'm using the store version.  I think my next step might be to uninstall, clear the data folder, and see if it is recognized then.

**Comment by normous** [comment] 2023-11-29 04:03
So I uninstalled the plug-in, removed all MicroSDeck dirs under homebrew, and rebooted the Deck. Reinstalled the plug-in, inserted the 1TB card, and it says no cards have been registered yet. I've tried a couple of times without any luck. As soon as I insert one of the other cards it picks it right up and recognizes it.

**Comment by jcc10** [comment] 2023-11-30 19:05
This is due to a recent SteamOS update (v3.5 I think) that changes how devices mount. The card is no longer guaranteed to mount to `/run/media/mmcblk0p1` and now shows up under `/run/media/deck/`

I recommend looking at ddotthomas/SteamDeck_SD_Card_Scanner#8 for how someone else fixed this exact bug, albeit for a standalone app instead of a decky plugin.

**Comment by normous** [comment] 2023-11-30 19:44
> The card is no longer guaranteed to mount to `/run/media/mmcblk0p1` and now shows up under `/run/media/deck/`

Good call!  I just confirmed that the SD card that doesn't show up for me does indeed mount under /run/media/deck/.

**Comment by CEbbinghaus** [comment] 2023-12-01 05:36
Oh crud. I read the log but it seems to be that I had forgotten to respond. Sorry been very busy with work. (note to self. Create bug template that includes asking for steamos version).

> This is due to a recent SteamOS update (v3.5 I think) that changes how devices mount. The card is no longer guaranteed to mount to /run/media/mmcblk0p1 and now shows up under /run/media/deck/

Thank you so much for that @jcc10. It seems this has originated because I run the latest version on my own device at all times since I want to know any bugs while I develop ahead of time. And it seems without even meaning to I have already solved this problem thanks to another user that used a custom label for their MicroSD card. 

I will see if I can push an update but for anyone else that wants it working again rn. Install the prerelease version manually by downloading the following plugin: `https://github.com/CEbbinghaus/MicroSDeck/suites/18531992656/artifacts/1075780756`
You simply paste that in the "download plugin from url" section in the decky settings. (you might need to enable developer mode). Then restart the steamdeck and you should be good. The UI has changed significantly and a lot of extra things are implemented but this bug should be fixed :3

**Comment by normous** [comment] 2023-12-02 03:25
> > Edit: I just did some more testing. When I insert the other cards it creates a symlink in /run/media to 'mmcblk0p1', but for the newer card it creates a symlink in /var/media 'Team 1TB' -> 'run/media/deck/Team 1TB'. But in either case the actual mount point is always in /run/media/deck/.
> 
> That does not sound good. I presume this card is showing up just fine for you in SteamOS? I wonder why it binds differently. But seeing as all other cards bind to `/run/media/deck` and they work for you I assume you are already running the latest version? That should have failed with the version on the store.

I just downloaded the preview version you linked above (0.9.7), and unfortunately the 1TB card still doesn't show. It does indeed show up and work correctly in SteamOS. I'm running OS ver. 3.5.7, build 20231122.1.

Be happy to test any other versions when you have one to try., or provide any other info I can. 

Also I like the changes to the front end! Looking very good.

**Comment by Arck0s** [comment] 2024-01-18 19:30
Good evening,
I have exactly the same problem with my SanDisk 512Gb card on a SteamDeck OLED 512Gb.
Nothing specific in the log

I use the MicroSDeck 0.9.1 version available on Deckyloader

**Comment by CEbbinghaus** [comment] 2024-01-18 23:31
Sorry guys, Been flat out with work. Hoping to get back onto it before Feb. Been having another reported problem of only some games showing up. There seems to be problems with how the games are read off the card (could well be that this is due to Steam changing something). I will update this Issue when I have something more concrete. Hold tight (and thank you for using MicroSDeck <3)

**Comment by Arck0s** [comment] 2024-01-20 08:58
Good morning,
I had the plugin update, unfortunately no change for me. I ejected the card, rebooted the console but no changes :(
I remain hopeful :)
Good luck to you

**Comment by CEbbinghaus** [comment] 2024-02-10 07:50
To update you all, Have had a little bit of time to work on this. I added a config & better logging which I will be extending with outputting a LOT more information. So the hope is that one of the next updates will include those changes and generate some log files that are actually useful. Sorry for the massive delay it has been a lot more hectic than I wanted. Best Regards,

**Comment by Arck0s** [comment] 2024-02-10 09:03
Thank you for the news. Good luck

**Comment by CEbbinghaus** [comment] 2024-02-14 09:56
@jfreuden merged a fix 4 days ago that ended up fixing a lot of problems. Seems to have been caused by capitalization in fields of the steam afc files. This might have been the root cause for this issue. in which case it might already be fixed. Trying the latest release could potentially resolve this.

In other news my PR is getting a lot closer to completion with way more logging happening. This means that if it wasn't fixed by the captialization PR then at least we will have more info on what is going wrong soon. Please try & report back <3

**Comment by normous** [comment] 2024-02-27 14:19
@CEbbinghaus What's the best way to test these changes? Would love to help.

**Comment by CEbbinghaus** [comment] 2024-02-27 14:30
@normous since the current latest is broken with TabMaster, I reccomend installing it via this url:
`https://github.com/CEbbinghaus/MicroSDeck/actions/runs/7920757620/artifacts/1249000345` (it just uses the following artifact: https://github.com/CEbbinghaus/MicroSDeck/actions/runs/7920757620)

If you do not use TabMaster & don't intend to any time soon. Then you can continue using the nighly link:
`https://nightly.link/CEbbinghaus/MicroSDeck/workflows/build/master/MicroSDeck.zip` both of which should work when plugged into the decky field for custom plugin download.

That should automatically install the latest version of MicroSDeck. Sorry I haven't published a new version on the official store yet. I am working on the documentation & some other smaller changes which I want to complete before officially releasing it under the 1.0.0 banner.

**Comment by CEbbinghaus** [comment] 2024-08-26 13:02
Closing as this issue has gone stale and the problem seems to be fixed

**Closed by CEbbinghaus** 2024-08-26 13:02 UTC
Labels: bug
